---

name: Test

on:
  - push

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.12.0-rc.1'

      - name: Dependencies
        run: mix deps.get

      - name: Problem Matcher
        run: >
          echo "::add-matcher::.github/problem-matchers.json"

      - name: Format
        run: mix format --check-formatted

  credo:
    name: Credo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.12.0-rc.1'

      - name: Dependencies
        run: mix deps.get

      - name: Problem Matcher
        run: >
          echo "::add-matcher::.github/problem-matchers.json"

      - name: Credo
        run: mix credo

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.12.0-rc.1'

      - name: Dependencies
        run: mix deps.get

      - name: Problem Matcher
        run: >
          echo "::add-matcher::.github/problem-matchers.json"

      - name: Dialyzer
        run: mix dialyzer

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.12.0-rc.1'

      - name: Dependencies
        run: mix deps.get

      - name: Problem Matcher
        run: >
          echo "::add-matcher::.github/problem-matchers.json"

      - name: Test
        run: mix test
